import { AsyncLocalStorage } from "node:async_hooks";
import { createHash, randomUUID } from "node:crypto";

/**
 * Request correlation (Phase 9 Unit 3, docs/DECISIONS.md D-099). One context per HTTP request, carried through the application
 * service, the orchestration, the provider call and the audit by `AsyncLocalStorage`, so no layer has to thread an id by hand.
 *
 * The request id is ALWAYS generated by the server: an inbound `x-request-id` is never trusted (it would let a caller choose an
 * audit key, forge a correlation or inject log content). The student is represented by a one-way reference, never the raw id.
 */
export interface RequestContext {
  requestId: string;
  method: string;
  /** The route TEMPLATE (e.g. `/v1/simulations/:id`), never the concrete path - concrete paths carry resource ids. */
  route: string;
  actorKind: "anonymous" | "student" | "staff";
  studentRef: string | null;
  examCode: string | null;
  startedAtMs: number;
}

const storage = new AsyncLocalStorage<RequestContext>();

export const newRequestId = (): string => randomUUID();

/** A short, one-way, stable reference to a student: correlates a student's events without writing the id itself. */
export function studentRef(studentId: string): string {
  return createHash("sha256").update(`ipmat-student-ref:${studentId}`).digest("hex").slice(0, 12);
}

export function runWithContext<T>(context: RequestContext, fn: () => T): T {
  return storage.run(context, fn);
}

export function currentContext(): RequestContext | undefined {
  return storage.getStore();
}

/** Records who the request turned out to be, once authentication has run. Mutates only the current request's context. */
export function updateContext(patch: Partial<Pick<RequestContext, "actorKind" | "studentRef" | "examCode" | "route">>): void {
  const ctx = storage.getStore();
  if (ctx) Object.assign(ctx, patch);
}
